
[env]
  TERM = "xterm-256color"

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 9.7

[font.normal]
family = "JetBrains Mono"
style = "Italic"

[selection]
save_to_clipboard = false

[window]
decorations = "none"
dynamic_title = true
opacity = 0.9

[scrolling]
history = 10000
multiplier = 3

[general]
live_config_reload = true

import = [
    "~/.config/alacritty/rosepine.toml",
]

[window.padding]
x = 6
y = 3

