live_config_reload = true

[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x787c99"
yellow = "0xe0af68"

[colors.primary]
background = "0x000009"
foreground = "0xa9b1d6"

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 9

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[selection]
save_to_clipboard = false

[window]
decorations = "none"
dynamic_title = true
opacity = 0.8

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 6
y = 6
