#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Polkit
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config top_padding         25
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

# Autostart
# Bar
~/.config/polybar/launch.sh &

# Notifications
# /usr/bin/dunst &

# Remaps
~/.local/scripts/remaps.sh

# Wallpaper
nitrogen --restore &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
# ~/.config/bspwm/scripts/low_bat_notifier.sh
